### ISSUE TITLE
Cloned CdsServiceClient has empty CurrentAccessToken after parent is disposed

### ISSUE THREAD

**Issue by stvonolf** [microsoft/PowerPlatform-CdsServiceClient#73]
Hi,
Not sure if this is by design or a bug, but if the parent CdsServiceClient is disposed, the CurrentAccessToken of the clone becomes empty.

Steps to reproduce (simplified):
```
var cdsServiceClient = new CdsServiceClient(...);
var clone = cdsServiceClient.Clone();
cdsServiceClient.Dispose();
clone.RetrieveMultiple(...); // leads to System.ServiceModel.Security.MessageSecurityException - empty token
```

Regards,
Stefan

**Comment by stvonolf** [comment]
The root cause seems to be the logic in the method SetClonedProperties in CdsConnectionService:

![image](https://user-images.githubusercontent.com/69305614/100341025-5462be00-2fdc-11eb-8c2e-24e56c3fc951.png)

Once the source client is disposed, CurrentAccessToken will return string.empty:
![image](https://user-images.githubusercontent.com/69305614/100341102-6a707e80-2fdc-11eb-8c93-9bfb697cd508.png)

**Comment by MattB-msft** [comment]
This is/was by design.  
The root connection which clones are created from is intended to be persisted,  whist's clones are created and destroyed from it at will.  That said, a number of the components of this design have changed as part of current work to port to MSAL. 

We will know more as to how this will work out when we have completed all the test code and paths for the updated auth stack.
