### ISSUE TITLE
CCdsServiceClient constructor hangs when using AuthType OAuth 

### ISSUE THREAD

**Issue by kirilvalev** [microsoft/PowerPlatform-CdsServiceClient#83]
Trying to create a connection using the following connection string. This same connection string works with the CrmServiceClient.

`string c = @"AuthType=OAuth;LoginPrompt=Auto;Integrated Security=true;url={URL};AppId={APP_GUID};RedirectURI=https://login.microsoftonline.com/common/oauth2/nativeclient";`

Then passing to CdsServiceClient:
`var cdsClient = new CdsServiceClient(c);`

The execution never returns from the constructor.

**Comment by MattB-msft** [comment]
You are asking it to use Windows Native authentication.   There have been a number of changes in MSAL in this area that have destabilized this flow in the client 

for your appId,  register https://localhost for the redirect URI, then use please use https://localhost for that value on the connect string. 

I believe our changes have propagated for this.

**Comment by kirilvalev** [comment]
Thank you. Just read in the Microsoft docs, that dotnet core does not support the native login experience yet, and that's why the redirect uri must point to https://localhost and use the browser for the login.

**Comment by julian-westermann** [comment]
I understand from the original comment, that OAuth is a supported authentication type of this lib? 
Because I get the error `Unsupported Connection request`  from `CdsServiceClient` when using the following connection string:

`$"AuthType=OAuth;Url={orgUrl};Username={orgEmail};Password={orgPwd};AppId={orgAppId};RedirectUri=app://{orgAppId};LoginPrompt=Never"; `

The `CrmServiceClient` works fine when using exactly the same connection string. Also using https://localhost as redirect uri doesn´t solve this issue. 
I want to use `CdsServiceClient` to establish a connection to a dynamics 365 online tenant within a .net core 3.1 azure function.
